export default {
  OPEN_MAIN_MENU: 'OPEN_MAIN_MENU',
  CHANGE_TAB: 'CHANGE_TAB',
  SET_THEME: 'SET_THEME',
  SET_AUTH: 'SET_AUTH',
  SET_PROFILE: 'SET_PROFILE',
  CHANGE_AUTH_INPUT: 'CHANGE_AUTH_INPUT',
  CLEAR_INPUT: 'CLEAR_INPUT',
}
