export default {
  SET_THEME: 'SET_THEME',
  SET_AUTH: 'SET_AUTH',
  SET_PROFILE: 'SET_PROFILE',
  CHANGE_AUTH_INPUT: 'CHANGE_AUTH_INPUT',
  CLEAR_INPUT: 'CLEAR_INPUT',
  SET_POKEMONS: 'SET_POKEMONS',
  SET_SINGLE_POKEMON: 'SET_SINGLE_POKEMON',
  CLEAR_POKEMONS: 'CLEAR_POKEMONS',
}
